(function () {
  'use strict';

  const STYLE_ID = 'at-header-branco-style';

  function getHeaderBrancoCss() {
    return [
      '@media screen and (min-width: 996px) {',
      '  .HeaderNavigationBarDropdown__item {',
      '    height: auto;',
      '    min-height: 228px;',
      '  }',
      '}',
      '.Glyph--user:before {',
      "  content: url('https://www.nespresso.com/shared_res/markets/it/b2c_b2b/icons/nespresso_icons/UI_ICONS_24px/24_USER/24_user_account.svg');",
      '}',
      '.Glyph--basket:before {',
      "  content: url('https://www.nespresso.com/shared_res/markets/it/b2c_b2b/icons/nespresso_icons/UI_ICONS_24px/24_SYMBOLS/24_symbols_misc_shoppingbag.svg');",
      '}',
      '.LoginDropdownButton:hover>.Glyph--user:before,',
      '.MiniBasketButton:hover>.Glyph--basket:before {',
      '  -webkit-filter: invert(1);',
      '  filter: invert(1);',
      '}',
      '#search-bar-button>span:before {',
      "  content: url('https://www.nespresso.com/shared_res/markets/it/b2c_b2b/icons/nespresso_icons/UI_ICONS_24px/24_SYMBOLS/24_symbols_action_search.svg');",
      '  height: 24px !important;',
      '  margin-right: 4px;',
      '  width: 25px !important;',
      '}',
      'span.text {',
      '  display: contents;',
      '}',
      '@media screen and (min-width: 996px) {',
      '  .search-bar-button svg {',
      '    display: none !important;',
      '  }',
      '}',
      '@media screen and (max-width: 995px) {',
      '  .search-bar-button span.text {',
      '    display: inline-block !important;',
      "    content: url('https://www.nespresso.com/shared_res/markets/it/b2c_b2b/icons/nespresso_icons/UI_ICONS_24px/24_SYMBOLS/24_symbols_action_search.svg');",
      '    margin-top: 20%;',
      '    margin-left: 15%;',
      '  }',
      '  .search-bar-button svg {',
      '    display: none !important;',
      '  }',
      '}',
      '#search-bar-button:hover>span:before {',
      '  -webkit-filter: invert(1);',
      '  filter: invert(1);',
      '}',
      'div.LoginDropdown__title {',
      '  color: #000;',
      '}',
      'nb-usp nb-icon svg {',
      '  margin-left: auto;',
      '  margin-right: auto;',
      '}',
      '#MachinesMenuItem>div>div>ul>li:nth-child(2)>ul>li:nth-child(2)>a,',
      '#AccessoriesMenuItem>div>div>ul>li:nth-child(2)>ul>li:nth-child(2)>a,',
      '#AccessoriesMenuItem>div>div>ul>li:nth-child(2)>ul>li:nth-child(3)>a,',
      '#AccessoriesMenuItem>div>div>ul>li:nth-child(1)>ul>li:nth-child(3)>a,',
      '#header .HeaderNavigationBarDropdown__medium-links-item a {',
      '  color: #257a57 !important;',
      '}',
      '.HeaderNavigationBar__nav {',
      '  margin-bottom: 0;',
      '}',
      '.nlc-container {',
      '  right: 30px !important;',
      '}',
      '@media screen and (max-width: 480px) {',
      '  .nlc-container {',
      '    right: 0 !important;',
      '  }',
      '}',
      '@media screen and (min-width: 996px) {',
      '  .HeaderNavigationBarDropdown__item--small {',
      '    height: 114px;',
      '    padding: 10px 20px;',
      '    display: block;',
      '    justify-content: center;',
      '    min-height: 114px;',
      '  }',
      '  #SummerMenuItem .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title,',
      '  #SpecialOfferMenuItem .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title,',
      '  #MachinesMenuItem .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title,',
      '  #CoffeeMenuItem .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title,',
      '  #AccessoriesMenuItem .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title,',
      '  #ServicesMenuItem .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title {',
      '    display: block;',
      '  }',
      '  #SummerMenuItem .HeaderNavigationBarDropdown__list,',
      '  #SpecialOfferMenuItem .HeaderNavigationBarDropdown__list,',
      '  #CoffeeMenuItem .HeaderNavigationBarDropdown__list,',
      '  #MachinesMenuItem .HeaderNavigationBarDropdown__list,',
      '  #AccessoriesMenuItem .HeaderNavigationBarDropdown__list,',
      '  #ServicesMenuItem .HeaderNavigationBarDropdown__list {',
      '    height: 245px;',
      '    margin-top: 0;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--medium,',
      '  .HeaderNavigationBarDropdown__item--medium-links,',
      '  .HeaderNavigationBarDropdown__item--small {',
      '    padding: 0;',
      '  }',
      '  .HeaderNavigationBarDropdown__medium-links-item:hover {',
      '    background: #cecece;',
      '    text-decoration: none;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--medium,',
      '  .HeaderNavigationBarDropdown__item--medium-links {',
      '    padding: 10px;',
      '    text-align: center;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--medium-links:first-child,',
      '  .HeaderNavigationBarDropdown__item--medium:first-child {',
      '    padding-left: 0;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--medium .HeaderNavigationBarDropdown__item-media {',
      '    line-height: 50px;',
      '    top: 0;',
      '    bottom: 0;',
      '    left: 0;',
      '    right: 0;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--small .HeaderNavigationBarDropdown__item-media {',
      '    padding: 0 10px !important;',
      '  }',
      '  .HeaderNavigationBarDropdown__item:after {',
      '    border-right: 1px solid #e6e6e6 !important;',
      '  }',
      '  #MachinesMenuItem .HeaderNavigationBarDropdown__item:after {',
      '    top: 10px;',
      '  }',
      '  .HeaderNavigationBarDropdown__medium-link {',
      '    padding: 5px 0;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--small-odd:before {',
      '    border-bottom: 1px solid #e6e6e6;',
      '    left: 0;',
      '    right: 0;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title,',
      '  .HeaderNavigationBarDropdown__item--medium .HeaderNavigationBarDropdown__item-title {',
      '    margin-bottom: 15px;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--small .HeaderNavigationBarDropdown__item-title:hover,',
      '  .HeaderNavigationBarDropdown__item-media:hover {',
      '    text-decoration: none;',
      '    background: none;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--medium-links {',
      '    padding-top: 10px;',
      '  }',
      '  .HeaderNavigationBarDropdown__medium-link,',
      '  .HeaderNavigationBarDropdown__item--small {',
      '    font-family: NespressoLucas;',
      '    font-weight: 700;',
      '  }',
      '  .HeaderNavigationBarDropdown__item--medium .HeaderNavigationBarDropdown__item-title {',
      '    font-family: NespressoLucas;',
      '    font-weight: 700;',
      '    padding: 15px;',
      '    text-transform: uppercase;',
      '  }',
      '  #RecyclingMenuItem .HeaderNavigationBarDropdown__item--medium-links .HeaderNavigationBarDropdown__item-title {',
      '    display: block;',
      '    font-size: 0.925em;',
      '    max-width: 80%;',
      '    margin-left: auto;',
      '    margin-right: auto;',
      '  }',
      '  #RecyclingMenuItem .HeaderNavigationBarDropdown__item--medium-links img {',
      '    width: 75px;',
      '    height: 75px;',
      '    margin-bottom: 1em;',
      '  }',
      '  #CoffeeMenuItem .HeaderNavigationBarDropdown__medium-links-item a {',
      '    color: #000 !important;',
      '  }',
      '  .HeaderNavigationBarDropdown__item-subtitle {',
      '    position: absolute;',
      '    left: 90px;',
      '    bottom: 20px;',
      '    color: #737373;',
      '    font-size: 0.9em;',
      '    margin: 0;',
      '  }',
      '}',
      '.MiniBasketDropdown__dropdown .BenefitMessage {',
      '  background-color: #f3f0eb;',
      '}',
      '.OrderLinksBanner {',
      '  display: none;',
      '}',
      '.HeaderNavigationBarDropdown__item--big {',
      '  width: 50% !important;',
      '}',
      '.HeaderNavigationBarDropdown__item--big img {',
      '  width: 345px !important;',
      '  height: 175px !important;',
      '}',
      '@media screen and (max-width: 995px) {',
      '  .HeaderNavigationBarDropdown__item--big {',
      '    width: auto !important;',
      '  }',
      '}',
      '.HeaderCountryMessage__other-country a {',
      '  color: #fff;',
      '  text-decoration: underline;',
      '}',
      'body,',
      '#main,',
      '#main-container {',
      '  background-color: #fff;',
      '}',
      '@media (max-width: 995px) {',
      '  .HeaderNavigationBar__nav {',
      '    bottom: 0;',
      '    background-color: #fff;',
      '  }',
      '  .HeaderNavigationBar__menu .HeaderNavigationBarItem__icon {',
      '    filter: invert(1);',
      '  }',
      '  .HeaderNavigationBar__menu {',
      '    background: #fff;',
      '    min-height: calc(100vh - 160px);',
      '  }',
      '  .HeaderNavigationBarItem__title {',
      '    color: #000;',
      '    min-width: 200px;',
      '  }',
      '  #PromotionsMenuItem .HeaderNavigationBarItem__title {',
      '    color: #ac0436 !important;',
      '    font-weight: bold;',
      '  }',
      '  #GiftingMenuItem .HeaderNavigationBarItem__title {',
      '    color: #876c43 !important;',
      '    font-weight: bold;',
      '  }',
      '  #GiftingMenuItem .HeaderNavigationBarItem__icon,',
      '  #PromotionsMenuItem .HeaderNavigationBarItem__icon {',
      '    -webkit-filter: none;',
      '    filter: none;',
      '  }',
      '  .Header__top {',
      '    background: #fff;',
      '  }',
      '  .Header__logo {',
      '    filter: invert(1);',
      '  }',
      '  .HeaderNavigationBar__switch {',
      '    background: #fff;',
      '  }',
      '  .HeaderNavigationBar__switch .BurgerSwitch__bars,',
      '  .HeaderNavigationBar__switch .BurgerSwitch__bars:before,',
      '  .HeaderNavigationBar__switch .BurgerSwitch__bars:after {',
      '    background-color: #000;',
      '  }',
      '  .BurgerSwitch--is-active .BurgerSwitch__bars {',
      '    background-color: transparent;',
      '  }',
      '  .LoginDropdownButton__icon,',
      '  .MiniBasketButton__basketIcon {',
      '    color: #000;',
      '  }',
      '  .MiniBasketButton--not-empty .MiniBasketButton__basketIcon {',
      '    color: #fff;',
      '  }',
      '  .search-bar-button svg,',
      '  .search-bar-button svg>* {',
      '    fill: #000;',
      '  }',
      '  .HeaderNavigationBarItem>button[aria-expanded="true"],',
      '  .HeaderNavigationBarItem:hover .HeaderNavigationBarItem__element {',
      '    background: #b2b2b2;',
      '  }',
      '  .HeaderNavigationBarDropdown {',
      '    background: #fff;',
      '  }',
      '  .Header__top-wrapper {',
      '    box-shadow: 0 0 5px #737272;',
      '  }',
      '  .HeaderNavigationBar__language-switcher {',
      '    background: #fff;',
      '    margin: 0;',
      '    padding: 20px;',
      '  }',
      '  button.LanguageSwitcher__button.active {',
      '    border-top: 0;',
      '    border-top-left-radius: 0;',
      '    border-top-right-radius: 0;',
      '  }',
      '  button.LanguageSwitcher__button.active .LanguageSwitcher__button-icon {',
      '    transform: rotate(180deg);',
      '  }',
      '  .HeaderNavigationBar__language-switcher-dropdown {',
      '    bottom: calc(100% - 20px);',
      '    left: 20px;',
      '    right: 20px;',
      '    width: auto;',
      '  }',
      '  .HeaderNavigationBar__nav {',
      '    box-shadow: 0 0 7px #777;',
      '  }',
      '}',
      '@media (min-width: 996px) {',
      '  .Header__top-wrapper .Header__logo {',
      '    filter: invert(100%);',
      '  }',
      '  .HeaderNavigationBar__nav {',
      '    margin-top: 90px;',
      '    background-color: #fff;',
      '  }',
      '  .HeaderNavigationBarItem {',
      '    display: flex;',
      '    align-items: center;',
      '    justify-content: center;',
      '    background: #fff;',
      '    color: #000;',
      '  }',
      '  .HeaderNavigationBarDropdown {',
      '    background: #fff;',
      '  }',
      '  ul.HeaderNavigationBar__menu {',
      '    display: flex;',
      '  }',
      '  .HeaderNavigationBarItem__title:after {',
      '    background: transparent;',
      '    content: " ";',
      '    display: block;',
      '    height: 3px;',
      '    margin-top: 3px;',
      '    width: 0%;',
      '  }',
      '  .HeaderNavigationBarItem__element:hover .HeaderNavigationBarItem__title:after {',
      '    background: #000;',
      '    width: 100%;',
      '    transition: all 0.25s ease-in-out;',
      '    animation: menuBar 0.25s normal forwards ease-in-out;',
      '  }',
      '  @keyframes menuBar {',
      '    from { width: 0px; }',
      '    to { width: 100%; }',
      '  }',
      '  .HeaderNavigationBarItem__icon {',
      '    display: none !important;',
      '  }',
      '  .HeaderNavigationBarItem__title {',
      '    text-transform: uppercase;',
      '  }',
      '  .HeaderNavigationBar {',
      '    background: #fff;',
      '  }',
      '  .HeaderNavigationBarItem__anchor,',
      '  .HeaderNavigationBarItem__button {',
      '    color: #000;',
      '    display: flex;',
      '    align-items: center;',
      '    justify-content: center;',
      '  }',
      '  .HeaderNavigationBarItem__title {',
      '    color: #000;',
      '    font-family: "NespressoLucas";',
      '    letter-spacing: 0.025em;',
      '    line-height: 1.125;',
      '    padding: 1em 0.5em;',
      '    margin: 0;',
      '  }',
      '  .HeaderNavigationBarItem:not(:first-child):before {',
      '    display: none;',
      '  }',
      '  .HeaderNavigationBarItem__element {',
      '    padding: 0 0.25em 0;',
      '    display: flex;',
      '    align-items: center;',
      '    justify-content: center;',
      '  }',
      '  li#PromotionsMenuItem .HeaderNavigationBarItem__title {',
      '    color: #ac0436 !important;',
      '  }',
      '  #PromotionsMenuItem:hover .HeaderNavigationBarItem__title:after {',
      '    background-color: #ac0436;',
      '  }',
      '  li#GiftingMenuItem .HeaderNavigationBarItem__title {',
      '    color: #876c43 !important;',
      '  }',
      '  #GiftingMenuItem:hover .HeaderNavigationBarItem__title:after {',
      '    background-color: #876c43;',
      '  }',
      '  .HeaderNavigationBarItem:hover,',
      '  .HeaderNavigationBarItem:hover .HeaderNavigationBarItem__anchor,',
      '  .HeaderNavigationBarItem:hover .HeaderNavigationBarItem__button {',
      '    background-color: #fff;',
      '  }',
      '  #header {',
      '    background: #fff;',
      '  }',
      '  .Header__top-wrapper {',
      '    background: #fff;',
      '    color: #000;',
      '  }',
      '  .MiniBasketButton,',
      '  .LoginDropdownButton,',
      '  .search-bar-button {',
      '    background: #fff;',
      '    color: #000;',
      '    border-color: #000;',
      '    border-radius: 50px;',
      '  }',
      '  .MiniBasketButton:hover,',
      '  .LoginDropdownButton:hover,',
      '  .search-bar-button:hover {',
      '    background: #000;',
      '    color: #fff;',
      '    border-color: #000;',
      '  }',
      '  .search-bar-button svg {',
      '    filter: invert(1);',
      '  }',
      '  .search-bar-button:hover svg {',
      '    fill: #fff;',
      '  }',
      '}',
      '@media screen and (min-width: 996px) {',
      '  .site-width,',
      '  .ResponsiveContainer,',
      '  .Header__top {',
      '    max-width: 72.5rem;',
      '    width: auto;',
      '  }',
      '  .Header__top-wrapper {',
      '    transition: box-shadow 0.25s ease-in-out;',
      '  }',
      '  .Header__top-wrapper.shadowed {',
      '    box-shadow: 0 0 8px #17171a0d, 0 2px 8px #17171a14;',
      '  }',
      '}',
      '.HeaderNavigationBar .HeaderNavigationBarItem:nth-child(1) {',
      '  background: none !important;',
      '  color: #fff;',
      '}',
    ].join('\n');
  }

  function injectStyles() {
    if (document.getElementById(STYLE_ID)) return;
    const style = document.createElement('style');
    style.id = STYLE_ID;
    style.textContent = getHeaderBrancoCss();
    document.head.appendChild(style);
  }

  if (document.head) {
    injectStyles();
  } else {
    document.addEventListener('DOMContentLoaded', injectStyles);
  }
})();
