let quizAnswers = {
  sessionId: "473kd",
  response: [
    {
      icon: "24/coffee/capsule-ol",
      heading: "Original",
      value: "original",
      description: "",
      chip_icon: "",
      chip_value: "",
      nextQuestion: 1,
      question_id: "technology",
      question_id_num: 0,
    },
    {
      icon: "",
      heading: "Equilibrado",
      value: "mild",
      description:
        "Menor nível de torra e características destacadas do grão de café.",
      chip_icon: "24/coffee/coffee-aroma",
      chip_value: "Equilibrado",
      nextQuestion: 2,
      question_id: "intensity",
      question_id_num: 1,
    },
    {
      icon: "",
      heading: "Às vezes",
      value: "yes",
      description: "",
      chip_icon: "",
      chip_value: "",
      nextQuestion: 3,
      question_id: "milk_coffee",
      question_id_num: 2,
    },
    {
      icon: "24/machine/allergens",
      heading: "Leite vegetal",
      value: "plant",
      description: "",
      chip_icon: "24/machine/allergens",
      chip_value: "Leite vegetal",
      nextQuestion: 4,
      question_id: "milk_type",
      question_id_num: 3,
    },
    {
      icon: "24/cupsize/cupsize-large-americano-ol",
      heading: "Longo",
      value: "long",
      description: "150ml a 535ml",
      chip_icon: "24/cupsize/cupsize-large-americano-ol",
      chip_value: "Longo",
      nextQuestion: 5,
      question_id: "cup_size",
      question_id_num: 4,
    },
    {
      icon: "",
      heading: "Sim",
      value: "yes",
      description: "",
      chip_icon: "32/sustainability/worldball",
      chip_value: "Origem única",
      nextQuestion: 6,
      question_id: "origins",
      question_id_num: 5,
    },
    [
      {
        icon: "24/coffeenote/vanilla",
        heading: "Aromatizado",
        value: "flavoured",
        description: "",
        chip_icon: "24/coffeenote/vanilla",
        chip_value: "Aromatizado",
        nextQuestion: 7,
        answer_id: "0",
        question_id: "coffee_types",
        question_id_num: 6,
      },
    ],
  ],
  questionPointer: 6,
  page: "result",
};
